Repository 100-hours-a-week/22-tenten-ai, pull requests merged in 2025-06, with the labels that each got.

#134 [DOCS] CICD 구축을 위한 환경변수 참조 변경
  core/prompt_templates/bot_posts_prompt.py
  core/prompt_templates/bot_recomments_prompt.py
  core/prompt_templates/youtube_summary_prompt.py
  main.py
  models/model_loader.py
  services/bot_posts_service.py
  services/bot_recomments_service.py
  services/youtube_summary_service.py
  utils/logging_discord.py
Labels: docs, AI

#137 [HOTFIX] Cloud Secret Manager .env 경로명 수정 #136
  Dockerfile
  models/model_loader.py
  services/bot_posts_service.py
  services/bot_recomments_service.py
  services/youtube_summary_service.py
  utils/logging_discord.py
Labels: !hotfix

#147 [HOTFIX] Dockerfile cmd 수정
  Dockerfile
Labels: !hotfix

#149 [FIX] env 환경변수 참조 경로 수정
  core/prompt_templates/bot_posts_prompt.py
  core/prompt_templates/bot_recomments_prompt.py
  core/prompt_templates/youtube_summary_prompt.py
  models/model_loader.py
  services/bot_posts_service.py
  services/bot_recomments_service.py
  services/youtube_summary_service.py
  utils/logging_discord.py
Labels: !hotfix

#151 Fix/#150 api dev mode recomments bot
  core/prompt_templates/bot_recomments_prompt.py
  models/model_loader.py
  services/bot_posts_service.py
  services/bot_recomments_service.py
  services/youtube_summary_service.py
Labels: fix, refactor, AI

#152 [FIX] 유투브 자막 라이브러리 업데이트
  requirements.txt
Labels: fix, AI

#156 Feature/#139 langgraph
  requirements.txt
  services/bot_posts_service.py
  services/bot_recomments_service.py
Labels: feature, AI
