Repository 100-hours-a-week/22-tenten-ai, pull requests merged in 2025-05, with the labels that each got.

#36 Feature/31 colab model serve
  .gitignore
  models/koalpha_loader.py
  requirements.txt
Labels: feature

#39 Feature/37 application entry point
  .gitignore
  api/endpoints/bot_chats_router.py
  api/endpoints/bot_comments_router.py
  api/endpoints/bot_posts_router.py
  api/endpoints/youtube_summary_router.py
  main.py
  requirements.txt
Labels: feature

#40 Featrue/38 socialbot posts prompt
  core/__init__.py
  core/__pycache__/__init__.cpython-311.pyc
  core/prompt_templates/__init__.py
  core/prompt_templates/__pycache__/__init__.cpython-311.pyc
  core/prompt_templates/__pycache__/bot_posts_prompt.cpython-311.pyc
  core/prompt_templates/bot_posts_prompt.py
  models/__init__.py
  models/__pycache__/__init__.cpython-311.pyc
  models/__pycache__/koalpha_loader.cpython-311.pyc
  requirements.txt
Labels: feature

#42 [CHORE] .gitignore에 __pycache__ 디렉토리 추가
  .gitignore
  core/__pycache__/__init__.cpython-311.pyc
  core/prompt_templates/__pycache__/__init__.cpython-311.pyc
  core/prompt_templates/__pycache__/bot_posts_prompt.cpython-311.pyc
  models/__pycache__/__init__.cpython-311.pyc
  models/__pycache__/koalpha_loader.cpython-311.pyc
Labels: remove

#44 Feature/43 create controller
  api/endpoints/bot_chats_router.py
  api/endpoints/bot_comments_router.py
  api/endpoints/bot_posts_router.py
  api/endpoints/controllers/bot_chats_controller.py
  api/endpoints/controllers/bot_comments_controller.py
  api/endpoints/controllers/bot_posts_controller.py
  api/endpoints/controllers/youtube_summary_controller.py
  api/endpoints/youtube_summary_router.py
  requirements.txt
  services/bot_chats_service.py
  services/bot_comments_service.py
  services/bot_posts_service.py
  services/youtube_summary_service.py
Labels: feature

#45 [FEAT] 소셜봇 prompt engineering
  core/prompt_templates/bot_posts_prompt.py
Labels: feature

#47 [STYLE] 라우터 엔드포인트 중복된 경로 제거
  api/endpoints/bot_chats_router.py
  api/endpoints/bot_comments_router.py
  api/endpoints/bot_posts_router.py
Labels: style

#50 Feature/48 create youtube summary
  requirements.txt
  services/youtube_summary_service.py
Labels: feature

#52 Fix/51 solving circular reference problem
  api/endpoints/controllers/bot_chats_controller.py
  api/endpoints/controllers/bot_comments_controller.py
  api/endpoints/controllers/bot_posts_controller.py
  api/endpoints/controllers/youtube_summary_controller.py
  schemas/bot_chats_schema.py
  schemas/bot_comments_schema.py
  schemas/bot_posts_schema.py
  schemas/youtube_summary_schema.py
  services/bot_chats_service.py
  services/bot_comments_service.py
  services/bot_posts_service.py
  services/youtube_summary_service.py
Labels: fix

#53 Feature/49 socialbot generate post
  api/endpoints/controllers/bot_posts_controller.py
  core/prompt_templates/bot_posts_prompt.py
  models/koalpha_loader.py
  services/bot_posts_service.py
Labels: feature

#55 Feature/48 create youtube summary
  core/prompt_templates/youtube_summary_prompt.py
  services/youtube_summary_service.py
Labels: feature

#61 [FIX] .env에서 설정한 'MODEL_NGROK_URL'이 매번 업데이트되도록 클래스 내 로컬 변수로 설정함.
  models/koalpha_loader.py
Labels: fix

#63 Breaking change/58 social bot api schema update
  api/endpoints/controllers/bot_posts_controller.py
  core/prompt_templates/bot_posts_prompt.py
  schemas/bot_chats_schema.py
  schemas/bot_comments_schema.py
  schemas/bot_common_schema.py
  schemas/bot_posts_schema.py
  services/bot_chats_service.py
  services/bot_comments_service.py
  services/bot_posts_service.py
  utils/error_handler.py
Labels: feature, !breaking change

#66 Feature/64 dividing chunks for long transcript
  core/prompt_templates/youtube_summary_prompt.py
  services/youtube_summary_service.py
Labels: feature

#67 Feature/54 socialbot generate comment
  api/endpoints/bot_comments_router.py
  api/endpoints/bot_recomments_router.py
  api/endpoints/controllers/bot_comments_controller.py
  api/endpoints/controllers/bot_recomments_controller.py
  core/prompt_templates/bot_comments_prompt.py
  core/prompt_templates/bot_recomments_prompt.py
  main.py
  schemas/bot_comments_schema.py
  schemas/bot_recomments_schema.py
  services/bot_comments_service.py
  services/bot_recomments_service.py
  utils/error_handler.py
Labels: feature

#70 [FEAT] CORS 미들웨어 설정
  main.py
Labels: feature

#74 Feature/73 gcp gpu vllm
  .gitignore
  api/endpoints/bot_chats_router.py
  api/endpoints/bot_posts_router.py
  api/endpoints/controllers/bot_chats_controller.py
  api/endpoints/controllers/bot_posts_controller.py
  api/endpoints/controllers/bot_recomments_controller.py
  api/endpoints/controllers/youtube_summary_controller.py
  core/prompt_templates/youtube_summary_prompt.py
  main.py
  models/koalpha_loader.py
  requirements-gcp.txt
  services/bot_chats_service.py
  services/bot_posts_service.py
  services/bot_recomments_service.py
  services/youtube_summary_service.py
Labels: feature, chore, AI

#76 [FIX] Controller 객체 생성 수정
  api/endpoints/bot_chats_router.py
  api/endpoints/bot_posts_router.py
  api/endpoints/bot_recomments_router.py
  api/endpoints/youtube_summary_router.py
Labels: fix, AI

#78 [REFACTOR] YouTubeSummaryRequest 타입 변경
  schemas/youtube_summary_schema.py
  services/youtube_summary_service.py
Labels: refactor, AI

#81 [FEAT] apply_chat_template 기반 messages -> prompt 자동 변환 지원
  models/koalpha_loader.py
Labels: feature, AI

#83 [FEAT] 프롬프트 버저닝을 위한 langfuse 도입 - colab 테스트 완료
  .gitignore
  core/prompt_templates/bot_posts_prompt.py
  core/prompt_templates/bot_recomments_prompt.py
  core/prompt_templates/youtube_summary_prompt.py
  requirements.txt
  services/bot_posts_service.py
  services/bot_recomments_service.py
  services/youtube_summary_service.py
Labels: feature, chore, AI

#86 [FIX] 소셜봇 응답을 정제하기 위해 후처리 코드 추가
  core/prompt_templates/bot_recomments_prompt.py
  models/koalpha_loader.py
  services/bot_posts_service.py
  services/bot_recomments_service.py
Labels: fix, AI

#91 [FIX] 엔드포인트 끝에 "/" 삭제
  api/endpoints/bot_chats_router.py
  api/endpoints/bot_posts_router.py
  api/endpoints/bot_recomments_router.py
Labels: fix, AI

#92 [FIX] colab - gcp 버전 모델 파라미터 통일
  models/koalpha_loader.py
Labels: fix, AI

#95 [FEAT] v1(MVP) 배포
  .gitignore
  .python-version
  api/endpoints/bot_chats_router.py
  api/endpoints/bot_posts_router.py
  api/endpoints/bot_recomments_router.py
  api/endpoints/controllers/bot_chats_controller.py
  api/endpoints/controllers/bot_posts_controller.py
  api/endpoints/controllers/bot_recomments_controller.py
  api/endpoints/controllers/youtube_summary_controller.py
  api/endpoints/youtube_summary_router.py
  core/__init__.py
  core/cache.py
  core/prompt_templates/__init__.py
  core/prompt_templates/bot_chats_prompt.py
  core/prompt_templates/bot_posts_prompt.py
  core/prompt_templates/bot_recomments_prompt.py
  core/prompt_templates/youtube_summary_prompt.py
  main.py
  models/__init__.py
  models/koalpha_loader.py
  requirements-gcp.txt
  requirements.txt
  schemas/bot_chats_schema.py
  schemas/bot_common_schema.py
  schemas/bot_posts_schema.py
  schemas/bot_recomments_schema.py
  schemas/youtube_summary_schema.py
  services/bot_chats_service.py
  services/bot_posts_service.py
  services/bot_recomments_service.py
  services/youtube_summary_service.py
  utils/error_handler.py
  utils/logger.py
Labels: feature, AI

#109 [AI - HOTFIX]discord webhook 설정
  .github/ISSUE_TEMPLATE/트러블-간략하게-요약해서-한-줄로-제목.md
  .gitignore
  README.md
  api/endpoints/discord_webhook_router.py
  main.py
  requirements-gcp.txt
  requirements.txt
  utils/exception_handler.py
  utils/logger_discord.py
  utils/logging_discord.py
Labels: !hotfix

#111 [HOTFIX] 디스코드 웹훅 전송 로컬 제외 시키기
  utils/logging_discord.py
Labels: !hotfix

#113 [HOTFIX] 디스코드 웹훅 전송 로컬 제외 코드 중 오타 수정
  utils/logging_discord.py
Labels: !hotfix

#115 [!HOTFIX]/ gemini api 연결
  main.py
  models/model_loader.py
  requirements.txt
  services/bot_chats_service.py
  services/bot_posts_service.py
  services/bot_recomments_service.py
  services/youtube_summary_service.py
Labels: feature, !hotfix, AI

#119 [FIX] protobuf 의존성 충돌 문제 해결
  requirements.txt
Labels: fix, chore, AI

#120 Release/v0.3.4
  .gitignore
  api/endpoints/discord_webhook_router.py
  main.py
  models/model_loader.py
  requirements-gcp.txt
  requirements.txt
  services/bot_chats_service.py
  services/bot_posts_service.py
  services/bot_recomments_service.py
  services/youtube_summary_service.py
  utils/exception_handler.py
  utils/logger_discord.py
  utils/logging_discord.py
Labels: feature, fix, AI

#123 [!!HOTFIX] discord webhook 보안
  main.py
  utils/logging_discord.py
Labels: !hotfix, AI

#124 Release/v0.3.5
  main.py
  utils/logging_discord.py
Labels: !hotfix, AI
