Repository 100-hours-a-week/22-tenten-ai, pull requests merged in 2025-07, with the labels that each got.

#154 [DOCS] Dockerfile 수정pip install requirements-gcp
  Dockerfile
Labels: docs

#162 [HOTFIX] Dockerfile install requirements.txt 명령어 실행시 오류
  Dockerfile
Labels: !hotfix

#171 [FEAT] Dockerfile 브랜치별 명령어 분기처리
  Dockerfile
  entrypoint.sh
Labels: feature

#172 [FEAT] Dockerfile 브랜치별 명령어 분기처리 feature 새로운 기능 추가(버그수정)
  Dockerfile
Labels: fix

#175 [Docs] 모델 교체에 따른 환경변수 참조 변경
  core/prompt_templates/bot_posts_prompt.py
  core/prompt_templates/bot_recomments_prompt.py
  core/prompt_templates/youtube_summary_prompt.py
  main.py
  models/model_loader.py
  services/bot_recomments_service.py
  services/youtube_summary_service.py
  utils/logging_discord.py
Labels: docs, AI

#177 [AI - DOCS] 모델 교체에 따른 명령어 변경
  entrypoint.sh
Labels: docs

#179 [FEAT] 소셜봇 채팅 기능 구현
  api/endpoints/bot_chats_router.py
  api/endpoints/controllers/bot_chats_controller.py
  core/prompt_templates/bot_chats_prompt.py
  core/sse_manager.py
  docs/bot_chats_service.md
  main.py
  requirements-gcp.txt
  schemas/bot_chats_schema.py
  services/bot_chats_service.py
  tests/test_bot_chats_service.py
Labels: feature, AI
